### ISSUE TITLE
As a user I want to see a landing page so that I have an intro to the game.

### ISSUE THREAD

**Issue by roshlarosh** [fac18/recycling-game#4]

**Comment by Oliversw** [comment]
Nice one @roshlarosh! The only thing that I would mention is trying to also include some acceptance criteria within the body of the issue.

For example, this issue could be something like:

- [ ] Landing page exists
   - [ ] contains header
   - [ ] contains into copy
   - [ ] contains landing image
   - [ ] contains footer

This is also a great place to include a screenshot from the Figma if that's applicable.

It doesn't need to be exactly like this, but the idea is that one of your fellow developers can look at the issue and be absolutely sure of exactly what they need to do :) You don't need to go overboard with detail, but I think there should at least be a sentence or so about the acceptance criteria within the issues :)

**Comment by roshlarosh** [comment]
@Oliversw Thank you Oliver.
Acceptance criteria:
- [ ] Should contain The title of the game: Reduce, reuse, recycle
- [ ] Should contain three buttons: Let's Play!, How to Play, Fun Facts
- [ ] Let's Play! button should redirect to the game screen 
- [ ] How to Play button should open the how to play modal
- [ ] Func facts button should open the fun facts modal 
- [ ] Should contain some background style including some svgs
